// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes, avoid_renaming_method_parameters, constant_identifier_names

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> _ar = {
  "onboarding": {
    "title": "من زرع الخير إلى \nحصاد الأمل",
    "description": "انضم إلى بستاني الخيرية لخلق فرق إيجابي في مجتمعك.",
    "continue": "متابعة",
    "title2": "بزكاة مالك، تُفتح \n أبواب البركة",
    "description2": "تصدق الآن مع مؤسسة بستاني الخيرية، فكل درهم يُضاعف الأجر ويُحيي الأمل",
    "login": "تسجيل دخول",
    "createAccount": "إنشاء حساب"
  },
  "signup": {
    "title": "إنشاء حساب",
    "usernameLabel": "اسم المستخدم",
    "usernameHint": "أدخل اسمك هنا",
    "emailLabel": "البريد الالكتروني",
    "emailHint": "example@email.com",
    "passwordLabel": "كلمة المرور",
    "passwordHint": "********",
    "submit": "إنشاء حساب جديد",
    "haveAccount": "لديك حساب سابق؟",
    "login": "تسجيل دخول"
  },
  "login": {
    "title": "أهلاً بعودتك",
    "emailLabel": "البريد الالكتروني",
    "emailHint": "example@email.com",
    "passwordLabel": "كلمة المرور",
    "passwordHint": "********",
    "forgotPassword": "هل نسيت كلمة المرور؟",
    "submit": "تسجيل دخول",
    "noAccount": "ليس لديك حساب سابق؟ ",
    "createAccount": "إنشاء حساب",
    "wrongCode": "رمز غير صحيح. يرجى إدخال رمز صالح مكون من 4 أرقام",
    "validation": {
      "nameRequired": "الاسم مطلوب",
      "nameMinLength": "الاسم يجب أن يكون على الأقل حرفين",
      "nameLettersOnly": "الاسم يجب أن يحتوي على أحرف ومسافات فقط",
      "countryRequired": "البلد مطلوب",
      "phoneRequired": "رقم الهاتف مطلوب",
      "phoneDigitsOnly": "رقم الهاتف يجب أن يحتوي على أرقام فقط",
      "phoneLengthWith0": "رقم الهاتف يجب أن يكون 10 أرقام عند البدء بصفر",
      "phoneLengthWithout0": "رقم الهاتف يجب أن يكون 9 أرقام"
    }
  },
  "forgotPassword": {
    "title": "نسيت كلمة المرور",
    "description": "يرجى إدخال بريدك الإلكتروني لتلقي رمز التأكيد لإعادة تعيين كلمة المرور.",
    "emailLabel": "البريد الالكتروني",
    "emailHint": "example@email.com",
    "submit": "تأكيد"
  },
  "verifyOtp": {
    "title": "تأكيد البريد الإلكتروني",
    "description": "تم إرسال رمز التحقق إلى البريد الإلكتروني:",
    "submit": "تأكيد",
    "resendCode": "إعادة إرسال الرمز"
  },
  "resetPassword": {
    "title": "كلمة المرور الجديدة",
    "description": "يرجى إدخال كلمة المرور الجديدة",
    "newPasswordLabel": "كلمة المرور الجديدة",
    "newPasswordHint": "********",
    "confirmPasswordLabel": "تأكيد كلمة المرور الجديدة",
    "confirmPasswordHint": "********",
    "submit": "تأكيد"
  },
  "validation": {
    "emailRequired": "البريد الإلكتروني مطلوب",
    "emailInvalid": "يرجى إدخال بريد إلكتروني صحيح",
    "passwordRequired": "كلمة المرور مطلوبة",
    "passwordMinLength": "كلمة المرور يجب أن تكون {minLength} أحرف على الأقل",
    "passwordRequireUpperCase": "كلمة المرور يجب أن تحتوي على حرف كبير واحد على الأقل",
    "passwordRequireLowerCase": "كلمة المرور يجب أن تحتوي على حرف صغير واحد على الأقل",
    "passwordRequireNumber": "كلمة المرور يجب أن تحتوي على رقم واحد على الأقل",
    "passwordRequireSpecialChar": "كلمة المرور يجب أن تحتوي على رمز خاص واحد على الأقل",
    "confirmPasswordRequired": "تأكيد كلمة المرور مطلوب",
    "confirmPasswordMismatch": "كلمتا المرور غير متطابقتين",
    "cardNumberRequired": "رقم البطاقة مطلوب",
    "cardNumberInvalid": "رقم البطاقة غير صحيح",
    "cardNumberLength": "رقم البطاقة يجب أن يكون بين 13 و 19 رقمًا",
    "cardExpiryRequired": "تاريخ الانتهاء مطلوب",
    "cardExpiryInvalid": "تاريخ الانتهاء غير صحيح (مثال: 12/25)",
    "cardExpiryInvalidMonth": "الشهر يجب أن يكون بين 01 و 12",
    "cardExpiryExpired": "البطاقة منتهية الصلاحية",
    "cardCvvRequired": "رمز التحقق مطلوب",
    "cardCvvInvalid": "رمز التحقق غير صحيح",
    "cardCvvLength": "رمز التحقق يجب أن يكون 3 أو 4 أرقام",
    "cardholderNameRequired": "اسم صاحب البطاقة مطلوب",
    "cardholderNameMinLength": "اسم صاحب البطاقة يجب أن يكون 3 أحرف على الأقل",
    "cardholderNameInvalid": "اسم صاحب البطاقة غير صحيح",
    "donationAmountRequired": "المبلغ مطلوب",
    "donationAmountInvalid": "يرجى إدخال مبلغ صحيح",
    "donationAmountMustBePositive": "المبلغ يجب أن يكون أكبر من صفر",
    "donationAmountExceedsRemaining": "المبلغ يتجاوز المبلغ المتبقي"
  },
  "navigation": {
    "home": "الرئيسية",
    "about": "من نحن",
    "projects": "مشاريع بستاني",
    "campaigns": "الحملات",
    "donationCategories": "أقسام التبرع",
    "contact": "تواصل معنا",
    "language": "العربيّة"
  },
  "home": {
    "sliderTitle": "مؤسسة بُستاني الخيرية",
    "sliderSubtitle": "لمعيشة أكثر أماناً",
    "sliderButton": "تعرف علينا",
    "heroTitle": "مؤسسة بستاني لخدمة المجتمع",
    "heroSubtitle": "حيث ينمو الحلم مع كل تبرع",
    "heroDonateButton": "تبرع الآن",
    "heroDonationSectionsButton": "أقسام التبرع",
    "mainTitleHighlight": "مؤسسة بستاني",
    "mainTitleRest": "لخدمات المجتمع",
    "mainDescription": "مؤسسة بستاني لخدمة المجتمع تزرع الأمل في كل بيت وطفل، حيث تحول تبرعاتكم إلى كفالة أسر محتاجة وتعليم وصحة للأطفال، إلى جانب دعم غذائي وإيوائي مستدام. أكثر من خمسمائة مستفيد يعيشون حياة أفضل كل شهر بفضل عطائكم، فمعًا ننمي المجتمع خطوة بخطوة.",
    "catalogFastDonate": "التبرع السريع",
    "catalogBostaniCampaigns": "حملات بستاني",
    "catalogZakat": "زكاة المال",
    "catalogFamilySponsorship": "كفالة أسرة",
    "mainCampaigns": "أهم الحملات",
    "viewAll": "الكل",
    "allCampaigns": "جميع الحملات",
    "campaignDetails": "تفاصيل الحملة",
    "bustaniProjects": "مشاريع بستاني",
    "allProjects": "جميع المشاريع",
    "bustaniAcademy": "أكادمية بستاني",
    "bustaniAcademyDesc": "شاركنا في إسعاد الأسر المحتاجة",
    "bustaniMedicalTeam": "فريق بستاني الطبي",
    "bustaniMedicalTeamDesc": "سلتك اليوم قد تكون فرحة أسرة غدًا",
    "orphanSponsorship": "كفالة الأيتام",
    "sponsorOrphanFamily": "اكفل أسرة يتيمة",
    "joinHappinessFamilies": "شاركنا في إسعاد الأسر المحتاجة",
    "campaign1Title": "حملة أضاحي العيد",
    "campaign1Desc": "شاركنا في إسعاد الأسر المحتاجة في أيام العيد",
    "campaign2Title": "حملة زادك واصل بمحبة",
    "campaign2Desc": "سلتك اليوم قد تكون فرحة أسرة غدًا",
    "campaign3Title": "حملة الشتاء الدافئ",
    "campaign3Desc": "ساهم في تدفئة قلوب المحتاجين في فصل الشتاء",
    "campaign4Title": "حملة إفطار صائم",
    "campaign4Desc": "كن سببًا في إفطار صائم واكسب الأجر العظيم",
    "zakatTitle": "زكاتك تغيّر حياة",
    "zakatDescription": "الزكاة ليست مجرد إنفاق... بل هي: عبادة تقرب إلى الله تطهير للنفس والمال جسر بين الأغنياء والفقراء ضمان لاستقرار المجتمع وعد إلهي بالبركة والمغفرة",
    "zakatSubtitle": "تبرّع الآن بزكاة أموالك من خلال مؤسسة بستاني لخدمة المجتمع",
    "donateNow": "تبرّع الآن"
  },
  "footer": {
    "contactUs": "اتصل بنا",
    "help": "المساعدة",
    "followUs": "تابعنا",
    "location": "سوريا، حلب",
    "email": "Ourstudio@hello.com",
    "phone": "+1 386-688-3295",
    "aboutBustani": "حول مؤسسة بستاني",
    "bustaniProjects": "مشاريع بستاني",
    "campaigns": "الحملات",
    "copyright": "مؤسسة بستاني لخدمة المجتمع - جميع الحقوق محفوظة 2023 - 2025"
  },
  "campaign": {
    "requiredAmount": "المبلغ المطلوب",
    "campaignNumber": "الحملة",
    "paid": "مدفوع",
    "remaining": "متبقي",
    "donate": "تبرع",
    "tabOverview": "نظرة عامة",
    "tabDetails": "تفاصيل",
    "tabDonations": "تبرعات",
    "tabComments": "تعليقات",
    "donationNumber": "رقم التبرع",
    "donor": "المتبرع",
    "donatedAmount": "المبلغ المتبرع به",
    "donorEmail": "الايميل",
    "overviewCampaignNumber": "رقم الحملة:",
    "overviewCategory": "التصنيف:",
    "overviewDepartment": "القسم المسؤول:",
    "overviewStatus": "الوضع الحالي:",
    "donationOptionsTitle": "خيارات التبرع",
    "donationUnspecifiedTitle": "التبرع بمبلغ لا على التعيين",
    "donationUnspecifiedDesc": "التبرع بمبلغ لا على التعيين دون غاية مخصصة",
    "donationRecurringTitle": "التبرع الشهري المتكرر",
    "donationRecurringDesc": "التبرع بمبلغ شهري متكرر تلقائي الدفع"
  },
  "fastDonate": {
    "title": "التبرع العام و السريع",
    "chooseDonationType": "اختر نوع التبرع:",
    "generalDonation": "تبرع عام",
    "oneTime": "تبرع لمرة واحدة",
    "weekly": "تبرع أسبوعي",
    "monthly": "تبرع شهري",
    "otherAmount": "مبلغ أخر",
    "processPayment": "إجراء عملية الدفع الآن",
    "enterAmountHint": "أدخل مبلغ التبرع بالدولار الأمريكي",
    "confirmDonation": "تأكيد التبرع",
    "donatedAmount": "المبلغ المتبرع به:",
    "totalAmount": "المبلغ الإجمالي:",
    "confirmAndContinue": "التأكيد والمتابعة",
    "confirmAndGoToPaid": "انتقل للدفع",
    "paymentMethods": "طرق الدفع",
    "paypal": "Paypal",
    "bankCard": "بطاقة بنكية"
  },
  "cardPayment": {
    "title": "معلومات البطاقة",
    "cardholderName": "اسم صاحب البطاقة",
    "cardholderNameHint": "أدخل الاسم كما هو مكتوب على البطاقة",
    "cardNumber": "رقم البطاقة",
    "cardNumberHint": "1234 5678 9012 3456",
    "expiryDate": "تاريخ الانتهاء",
    "expiryDateHint": "مثال: 12/25",
    "cvv": "رمز التحقق من البطاقة",
    "cvvHint": "مثال: 123",
    "confirmPayment": "تأكيد الدفع"
  },
  "calculator": {
    "title": "الزكاة",
    "calculatorOption": "حاسبة الزكاة",
    "calculatorDesc": "قم بإضافة أصولك النقدية وغير النقدية لحساب زكاة المال المترتب عليك دفعها",
    "manualOption": "إدخال مبلغ الزكاة يدوياً",
    "manualDesc": "أدخل مبلغ الزكاة مباشرة إذا كنت تعرف المبلغ المحدد",
    "addAsset": "إضافة أصل",
    "addAssetButton": "إضافة",
    "assetCategory": "تصنيف الأصل",
    "assetCategoryHint": "أصل نقدي",
    "assetValue": "قيمة الأصل النقدي",
    "assetValueHint": "قيمة الأصل النقدي",
    "cashAsset": "أصل نقدي",
    "nonCashAsset": "أصل غير نقدي",
    "goldAsset": "ذهب",
    "silverAsset": "فضة",
    "stocksAsset": "أسهم",
    "realEstateAsset": "عقارات",
    "goldKarat": "عيار الذهب",
    "goldKaratHint": "اختر عيار الذهب",
    "karat24": "عيار 24",
    "karat22": "عيار 22",
    "karat21": "عيار 21",
    "karat18": "عيار 18",
    "weightInGrams": "الوزن بالجرام",
    "weightInGramsHint": "أدخل الوزن بالجرام",
    "goldPricePerGram": "سعر الذهب للجرام",
    "goldPricePerGramHint": "اختر مصدر السعر",
    "goldPriceSource": "مصدر سعر الذهب",
    "automaticPrice": "تحديث تلقائي من السوق العالمي",
    "manualPrice": "تحديد يدوي",
    "enterManualPrice": "أدخل السعر يدوياً",
    "silverWeightInGrams": "وزن الفضة بالجرام",
    "silverWeightInGramsHint": "أدخل الوزن بالجرام",
    "silverPricePerGram": "سعر الفضة للجرام",
    "silverPricePerGramHint": "اختر مصدر السعر",
    "silverPriceSource": "مصدر سعر الفضة",
    "shareCount": "عدد الأسهم",
    "shareCountHint": "أدخل عدد الأسهم",
    "sharePrice": "سعر السهم",
    "sharePriceHint": "أدخل سعر السهم",
    "shares": "سهم",
    "assetTotalValue": "القيمة الإجمالية",
    "zakatAmount": "مبلغ الزكاة",
    "totalAssets": "إجمالي الأصول",
    "totalZakat": "إجمالي الزكاة",
    "deleteAssetTitle": "حذف الأصل",
    "deleteAssetMessage": "هل أنت متأكد من حذف هذا الأصل؟",
    "cancel": "إلغاء",
    "delete": "حذف",
    "selectCategoryError": "يرجى اختيار تصنيف الأصل",
    "fillAllFieldsError": "يرجى ملء جميع الحقول المطلوبة",
    "enterValidValueError": "يرجى إدخال قيمة صحيحة",
    "errorAddingAsset": "حدث خطأ أثناء إضافة الأصل",
    "donateZakat": "التبرع بمبلغ الزكاة",
    "donateAmount": "التبرع بمبلغ"
  },
  "bottomNav": {
    "home": "الرئيسية",
    "donate": "تبرع",
    "menu": "القائمة"
  },
  "subcategories_campaign": {
    "pageTitle": "الحملات",
    "allCampaigns": "جميع الحالات",
    "medicalCampaigns": "الحملات الطبية",
    "humanitarianCampaigns": "الحملات الإنسانية",
    "orphanSupportCampaigns": "حملات دعم الأيتام",
    "campaignNumber": "الحملة",
    "requiredAmount": "المطلوب",
    "paidAmount": "مدفوع",
    "remainingAmount": "متبقي",
    "donate": "تبرع",
    "foodBasketCampaign": "حملة السلل الغذائية",
    "foodBasketDescription": "تحت شعار مؤسسة بستاني لخدمات المجتمع، انطلقت حملة السلال الغذائية لتقديم الدعم للأسر المحتاجة وتخفيف الأعباء المعيشية عنها، من خلال توزيع مواد غذائية أساسية تضمن لهم حياة كريمة خلال الأزمات والمواسم الصعبة"
  },
  "getKnownUs": {
    "pageTitle": "تعرف علينا",
    "articleTitle": "استخدم هذا المولد بحرية لتسريع عملية النمذجة والعرض",
    "articleDate": "04 تشرين الثاني 2025",
    "articleSubtitle": "استخدم هذا المولد بحرية لتسريع عملية النمذجة والعرض. النص العربي هنا يستخدم لعرض شكل…",
    "paragraph1": "استخدم هذا المولد بحرية لتسريع عملية النمذجة والعرض. يمكنك التحكم بطول الفقرة وعدد الأسطر بما يناسب واجهتك. النص العربي هنا يستخدم لعرض شكل…",
    "paragraph2": "استخدم هذا المولد بحرية لتسريع عملية النمذجة والعرض. يمكنك التحكم بطول الفقرة وعدد الأسطر بما يناسب واجهتك. النص العربي هنا يستخدم لعرض شكل…",
    "paragraph3": "استخدم هذا المولد بحرية لتسريع عملية النمذجة والعرض. يمكنك التحكم بطول الفقرة وعدد الأسطر بما يناسب واجهتك. النص العربي هنا يستخدم لعرض شكل…",
    "paragraph4": "استخدم هذا المولد بحرية لتسريع عملية النمذجة والعرض. يمكنك التحكم بطول الفقرة وعدد الأسطر بما يناسب واجهتك. النص العربي هنا يستخدم لعرض شكل…",
    "paragraph5Highlight": "استخدم هذا المولد بحرية لتسريع عملية النمذجة والعرض.",
    "paragraph5Normal": "يمكنك التحكم بطول الفقرة وعدد الأسطر بما يناسب واجهتك. النص العربي هنا يستخدم لعرض شكل…",
    "paragraph6": "استخدم هذا المولد بحرية لتسريع عملية النمذجة والعرض.",
    "share": "شارك"
  },
  "comments": {
    "placeholder": "اكتب تعليقك هنا...",
    "addComment": "إضافة تعليق"
  },
  "menu": {
    "pageTitle": "القائمة",
    "language": "اللغة",
    "theme": "المظهر",
    "selectLanguage": "اختر اللغة",
    "selectTheme": "اختر المظهر",
    "lightMode": "الوضع الفاتح",
    "darkMode": "الوضع الداكن",
    "systemMode": "وضع النظام",
    "systemModeDesc": "يتبع إعدادات النظام",
    "transparencyFile": "ملف الشفافية",
    "campaigns": "الحملات",
    "cases": "الحالات",
    "guarantees": "الكفالات",
    "projects": "المشاريع",
    "faq": "الأسئلة الشائعة",
    "contactUs": "تواصل معنا",
    "termsAndConditions": "الشروط والأحكام",
    "privacyPolicy": "سياسة الخصوصية",
    "chatWithSupport": "الدردشة مع فريق الدعم",
    "sendFeedback": "أرسل أقتراح او تقييم",
    "userName": "مصطفى حصرية"
  }
};
static const Map<String,dynamic> _en = {
  "onboarding": {
    "title": "From planting good to harvesting hope",
    "description": "Join Bosstani Charity to make a positive difference in your community.",
    "continue": "Continue",
    "title2": "With your Zakat, the doors of blessing open",
    "description2": "Donate now with Bosstani Charity Foundation. Every dirham multiplies reward and revives hope.",
    "login": "Login",
    "createAccount": "Create Account"
  },
  "signup": {
    "title": "Create Account",
    "usernameLabel": "Username",
    "usernameHint": "Enter your name",
    "emailLabel": "Email",
    "emailHint": "example@email.com",
    "passwordLabel": "Password",
    "passwordHint": "********",
    "submit": "Create New Account",
    "haveAccount": "Already have an account? ",
    "login": "Login"
  },
  "login": {
    "title": "Welcome back",
    "emailLabel": "Email",
    "emailHint": "example@email.com",
    "passwordLabel": "Password",
    "passwordHint": "********",
    "forgotPassword": "Forgot password?",
    "submit": "Login",
    "noAccount": "Don't have an account? ",
    "createAccount": "Create Account",
    "wrongCode": "Invalid code. Please enter a valid 4-digit code",
    "validation": {
      "nameRequired": "Name is required",
      "nameMinLength": "Name must be at least 2 characters",
      "nameLettersOnly": "Name must contain only letters and spaces",
      "countryRequired": "Country is required",
      "phoneRequired": "Phone number is required",
      "phoneDigitsOnly": "Phone number must contain only digits",
      "phoneLengthWith0": "Phone number must be 10 digits when starting with 0",
      "phoneLengthWithout0": "Phone number must be 9 digits"
    }
  },
  "forgotPassword": {
    "title": "Forgot Password",
    "description": "Please enter your email to receive the verification code to reset your password.",
    "emailLabel": "Email",
    "emailHint": "example@email.com",
    "submit": "Confirm"
  },
  "verifyOtp": {
    "title": "Verify Email",
    "description": "Verification code sent to email:",
    "submit": "Confirm",
    "resendCode": "Resend Code"
  },
  "resetPassword": {
    "title": "New Password",
    "description": "Please enter your new password",
    "newPasswordLabel": "New Password",
    "newPasswordHint": "********",
    "confirmPasswordLabel": "Confirm New Password",
    "confirmPasswordHint": "********",
    "submit": "Confirm"
  },
  "validation": {
    "emailRequired": "Email is required",
    "emailInvalid": "Please enter a valid email address",
    "passwordRequired": "Password is required",
    "passwordMinLength": "Password must be at least {minLength} characters",
    "passwordRequireUpperCase": "Password must contain at least one uppercase letter",
    "passwordRequireLowerCase": "Password must contain at least one lowercase letter",
    "passwordRequireNumber": "Password must contain at least one number",
    "passwordRequireSpecialChar": "Password must contain at least one special character",
    "confirmPasswordRequired": "Confirm password is required",
    "confirmPasswordMismatch": "Passwords do not match",
    "cardNumberRequired": "Card number is required",
    "cardNumberInvalid": "Invalid card number",
    "cardNumberLength": "Card number must be between 13 and 19 digits",
    "cardExpiryRequired": "Expiry date is required",
    "cardExpiryInvalid": "Invalid expiry date (e.g., 12/25)",
    "cardExpiryInvalidMonth": "Month must be between 01 and 12",
    "cardExpiryExpired": "Card has expired",
    "cardCvvRequired": "CVV is required",
    "cardCvvInvalid": "Invalid CVV",
    "cardCvvLength": "CVV must be 3 or 4 digits",
    "cardholderNameRequired": "Cardholder name is required",
    "cardholderNameMinLength": "Cardholder name must be at least 3 characters",
    "cardholderNameInvalid": "Invalid cardholder name",
    "donationAmountRequired": "Amount is required",
    "donationAmountInvalid": "Please enter a valid amount",
    "donationAmountMustBePositive": "Amount must be greater than zero",
    "donationAmountExceedsRemaining": "Amount exceeds remaining amount"
  },
  "navigation": {
    "home": "Home",
    "about": "About Us",
    "projects": "Bustani Projects",
    "campaigns": "Campaigns",
    "donationCategories": "Donation Categories",
    "contact": "Contact Us",
    "language": "English"
  },
  "home": {
    "sliderTitle": "Bostany Charity\n Foundation",
    "sliderSubtitle": "For a Safer Life",
    "sliderButton": "Learn About Us",
    "heroTitle": "Bustani Foundation for Community Service",
    "heroSubtitle": "Where the dream grows with every donation",
    "heroDonateButton": "Donate Now",
    "heroDonationSectionsButton": "Donation Sections",
    "mainTitleHighlight": "Bustani Foundation",
    "mainTitleRest": "for Community Services",
    "mainDescription": "Bustani Foundation for Community Service plants hope in every home and child, transforming your donations into family sponsorships, education and healthcare for children, along with sustainable food and shelter support. More than five hundred beneficiaries live better lives every month thanks to your generosity. Together, we grow the community step by step.",
    "catalogFastDonate": "Quick Donate",
    "catalogBostaniCampaigns": "Bostany Campaigns",
    "catalogZakat": "Zakat",
    "catalogFamilySponsorship": "Family Sponsorship",
    "mainCampaigns": "Main Campaigns",
    "viewAll": "View All",
    "allCampaigns": "All Campaigns",
    "campaignDetails": "Campaign Details",
    "bustaniProjects": "Bustani Projects",
    "allProjects": "All Projects",
    "bustaniAcademy": "Bustani Academy",
    "bustaniAcademyDesc": "Join us in bringing happiness to families in need",
    "bustaniMedicalTeam": "Bustani Medical Team",
    "bustaniMedicalTeamDesc": "Your basket today may be a family's joy tomorrow",
    "orphanSponsorship": "Orphan Sponsorship",
    "sponsorOrphanFamily": "Sponsor an Orphan Family",
    "joinHappinessFamilies": "Join us in bringing happiness to families in need",
    "campaign1Title": "Eid Sacrifice Campaign",
    "campaign1Desc": "Join us in bringing joy to needy families during Eid",
    "campaign2Title": "Share Your Food with Love Campaign",
    "campaign2Desc": "Your basket today may be a family's joy tomorrow",
    "campaign3Title": "Warm Winter Campaign",
    "campaign3Desc": "Help warm the hearts of those in need during winter",
    "campaign4Title": "Feed a Fasting Person Campaign",
    "campaign4Desc": "Be the reason someone breaks their fast and earn great reward",
    "zakatTitle": "Your Zakat Changes Lives",
    "zakatDescription": "Zakat is not just spending... it is: Worship that brings you closer to Allah, Purification of the soul and wealth, A bridge between the rich and the poor, A guarantee for community stability, A divine promise of blessings and forgiveness",
    "zakatSubtitle": "Donate your Zakat now through Bustani Foundation for Community Service",
    "donateNow": "Donate Now"
  },
  "footer": {
    "contactUs": "Contact Us",
    "help": "Help",
    "followUs": "Follow Us",
    "location": "Syria, Aleppo",
    "email": "Ourstudio@hello.com",
    "phone": "+1 386-688-3295",
    "aboutBustani": "About Bustani Foundation",
    "bustaniProjects": "Bustani Projects",
    "campaigns": "Campaigns",
    "copyright": "Bustani Foundation for Community Service - All Rights Reserved 2023 - 2025"
  },
  "campaign": {
    "requiredAmount": "Required Amount",
    "campaignNumber": "Campaign",
    "paid": "Paid",
    "remaining": "Remaining",
    "donate": "Donate",
    "tabOverview": "Overview",
    "tabDetails": "Details",
    "tabDonations": "Donations",
    "tabComments": "Comments",
    "donationNumber": "Donation #",
    "donor": "Donor",
    "donatedAmount": "Donated Amount",
    "donorEmail": "Email",
    "overviewCampaignNumber": "Campaign Number:",
    "overviewCategory": "Category:",
    "overviewDepartment": "Department:",
    "overviewStatus": "Current Status:",
    "donationOptionsTitle": "Donation Options",
    "donationUnspecifiedTitle": "Unspecified Donation",
    "donationUnspecifiedDesc": "Donate an unspecified amount without a specific purpose",
    "donationRecurringTitle": "Recurring Monthly Donation",
    "donationRecurringDesc": "Donate a recurring monthly amount with automatic payment"
  },
  "fastDonate": {
    "title": "General & Fast Donation",
    "chooseDonationType": "Choose donation type:",
    "generalDonation": "General Donation",
    "oneTime": "One-time Donation",
    "weekly": "Weekly Donation",
    "monthly": "Monthly Donation",
    "otherAmount": "Other Amount",
    "processPayment": "Process Payment Now",
    "enterAmountHint": "Enter donation amount in USD",
    "confirmDonation": "Confirm Donation",
    "donatedAmount": "Donated Amount:",
    "totalAmount": "Total Amount:",
    "confirmAndContinue": "Confirm and Continue",
    "confirmAndGoToPaid": "Continue and paid",
    "paymentMethods": "Payment Methods",
    "paypal": "Paypal",
    "bankCard": "Bank Card"
  },
  "cardPayment": {
    "title": "Card Information",
    "cardholderName": "Cardholder Name",
    "cardholderNameHint": "Enter name as shown on card",
    "cardNumber": "Card Number",
    "cardNumberHint": "1234 5678 9012 3456",
    "expiryDate": "Expiry Date",
    "expiryDateHint": "e.g., 12/25",
    "cvv": "Card Verification Code",
    "cvvHint": "e.g., 123",
    "confirmPayment": "Confirm Payment"
  },
  "calculator": {
    "title": "Zakat",
    "calculatorOption": "Zakat Calculator",
    "calculatorDesc": "Add your cash and non-cash assets to calculate the zakat amount you need to pay",
    "manualOption": "Manual Zakat Entry",
    "manualDesc": "Enter the zakat amount directly if you know the specific amount",
    "addAsset": "Add Asset",
    "addAssetButton": "Add",
    "assetCategory": "Asset Category",
    "assetCategoryHint": "Cash Asset",
    "assetValue": "Cash Asset Value",
    "assetValueHint": "Cash Asset Value",
    "cashAsset": "Cash Asset",
    "nonCashAsset": "Non-Cash Asset",
    "goldAsset": "Gold",
    "silverAsset": "Silver",
    "stocksAsset": "Stocks",
    "realEstateAsset": "Real Estate",
    "goldKarat": "Gold Karat",
    "goldKaratHint": "Select Gold Karat",
    "karat24": "24 Karat",
    "karat22": "22 Karat",
    "karat21": "21 Karat",
    "karat18": "18 Karat",
    "weightInGrams": "Weight in Grams",
    "weightInGramsHint": "Enter weight in grams",
    "goldPricePerGram": "Gold Price Per Gram",
    "goldPricePerGramHint": "Select price source",
    "goldPriceSource": "Gold Price Source",
    "automaticPrice": "Automatic Update from Global Market",
    "manualPrice": "Manual Entry",
    "enterManualPrice": "Enter price manually",
    "silverWeightInGrams": "Silver Weight in Grams",
    "silverWeightInGramsHint": "Enter weight in grams",
    "silverPricePerGram": "Silver Price Per Gram",
    "silverPricePerGramHint": "Select price source",
    "silverPriceSource": "Silver Price Source",
    "shareCount": "Number of Shares",
    "shareCountHint": "Enter number of shares",
    "sharePrice": "Share Price",
    "sharePriceHint": "Enter share price",
    "shares": "shares",
    "assetTotalValue": "Total Value",
    "zakatAmount": "Zakat Amount",
    "totalAssets": "Total Assets",
    "totalZakat": "Total Zakat",
    "deleteAssetTitle": "Delete Asset",
    "deleteAssetMessage": "Are you sure you want to delete this asset?",
    "cancel": "Cancel",
    "delete": "Delete",
    "selectCategoryError": "Please select an asset category",
    "fillAllFieldsError": "Please fill all required fields",
    "enterValidValueError": "Please enter a valid value",
    "errorAddingAsset": "An error occurred while adding the asset",
    "donateZakat": "Donate Zakat Amount",
    "donateAmount": "Donate Amount"
  },
  "bottomNav": {
    "home": "Home",
    "donate": "Donate",
    "menu": "Menu"
  },
  "subcategories_campaign": {
    "pageTitle": "Campaigns",
    "allCampaigns": "All Cases",
    "medicalCampaigns": "Medical Campaigns",
    "humanitarianCampaigns": "Humanitarian Campaigns",
    "orphanSupportCampaigns": "Orphan Support Campaigns",
    "campaignNumber": "Campaign",
    "requiredAmount": "Required",
    "paidAmount": "Paid",
    "remainingAmount": "Remaining",
    "donate": "Donate",
    "foodBasketCampaign": "Food Basket Campaign",
    "foodBasketDescription": "Under the motto of Bustani Foundation for Community Service, the Food Basket Campaign was launched to provide support to needy families and ease their living burdens by distributing essential food items ensuring them a dignified life during crises and difficult seasons"
  },
  "getKnownUs": {
    "pageTitle": "Get to Know Us",
    "articleTitle": "Use this generator freely to speed up the modeling and rendering process",
    "articleDate": "November 04, 2025",
    "articleSubtitle": "Use this generator freely to speed up the modeling and rendering process. Arabic text here is used to display form…",
    "paragraph1": "Use this generator freely to speed up the modeling and rendering process. You can control the length of the paragraph and the number of lines to suit your interface. Arabic text here is used to display form…",
    "paragraph2": "Use this generator freely to speed up the modeling and rendering process. You can control the length of the paragraph and the number of lines to suit your interface. Arabic text here is used to display form…",
    "paragraph3": "Use this generator freely to speed up the modeling and rendering process. You can control the length of the paragraph and the number of lines to suit your interface. Arabic text here is used to display form…",
    "paragraph4": "Use this generator freely to speed up the modeling and rendering process. You can control the length of the paragraph and the number of lines to suit your interface. Arabic text here is used to display form…",
    "paragraph5Highlight": "Use this generator freely to speed up the modeling and rendering process.",
    "paragraph5Normal": "You can control the length of the paragraph and the number of lines to suit your interface. Arabic text here is used to display form…",
    "paragraph6": "Use this generator freely to speed up the modeling and rendering process.",
    "share": "Share"
  },
  "comments": {
    "placeholder": "Write your comment here...",
    "addComment": "Add Comment"
  },
  "menu": {
    "pageTitle": "Menu",
    "language": "Language",
    "theme": "Theme",
    "selectLanguage": "Select Language",
    "selectTheme": "Select Theme",
    "lightMode": "Light Mode",
    "darkMode": "Dark Mode",
    "systemMode": "System Mode",
    "systemModeDesc": "Follow system settings",
    "transparencyFile": "Transparency File",
    "campaigns": "Campaigns",
    "cases": "Cases",
    "guarantees": "Guarantees",
    "projects": "Projects",
    "faq": "FAQ",
    "contactUs": "Contact Us",
    "termsAndConditions": "Terms and Conditions",
    "privacyPolicy": "Privacy Policy",
    "chatWithSupport": "Chat with Support Team",
    "sendFeedback": "Send Suggestion or Feedback",
    "userName": "Mustafa Hasriah"
  }
};
static const Map<String, Map<String,dynamic>> mapLocales = {"ar": _ar, "en": _en};
}
